services:
  postgres:
    image: postgres:16
    container_name: collector-market-postgres
    environment:
      POSTGRES_DB: collector_market_dev
      POSTGRES_USER: collector
      POSTGRES_PASSWORD: collector
    ports:
      - "5432:5432"
    volumes:
      - collector-market-postgres-data:/var/lib/postgresql/data

volumes:
  collector-market-postgres-data: